"""create quality tables

Revision ID: 2440a194d66a
Revises: e5df279c2345
Create Date: 2026-04-27 11:16:45.665080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2440a194d66a'
down_revision: Union[str, Sequence[str], None] = 'e5df279c2345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_name', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_run_id', sa.Integer(), nullable=False),
    sa.Column('missing_values_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_row_count', sa.Integer(), nullable=False),
    sa.Column('empty_text_values_count', sa.Integer(), nullable=False),
    sa.Column('whitespace_text_values_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quality_run_id'], ['quality_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quality_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_issues')
    op.drop_table('quality_runs')
    # ### end Alembic commands ###
