"""create text features table

Revision ID: 2e3d4fd10f05
Revises: c18fb53b8693
Create Date: 2026-05-05 00:33:52.261291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3d4fd10f05'
down_revision: Union[str, Sequence[str], None] = 'c18fb53b8693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.DateTime(), nullable=False),
    sa.Column('title_length', sa.Integer(), nullable=False),
    sa.Column('description_length', sa.Integer(), nullable=False),
    sa.Column('title_word_count', sa.Integer(), nullable=False),
    sa.Column('description_word_count', sa.Integer(), nullable=False),
    sa.Column('has_description', sa.Boolean(), nullable=False),
    sa.Column('description_is_empty', sa.Boolean(), nullable=False),
    sa.Column('has_salary_mention', sa.Boolean(), nullable=False),
    sa.Column('has_schedule_mention', sa.Boolean(), nullable=False),
    sa.Column('has_requirements_mention', sa.Boolean(), nullable=False),
    sa.Column('has_benefits_mention', sa.Boolean(), nullable=False),
    sa.Column('has_call_to_action', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_run_id', 'client_id', 'company_id', 'vacancy_id', 'date_day', name='uq_text_features_feature_run_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_features')
    # ### end Alembic commands ###
