"""create validation tables

Revision ID: 3d04ec53c985
Revises: e27217ff30b5
Create Date: 2026-04-25 10:43:38.063211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d04ec53c985'
down_revision: Union[str, Sequence[str], None] = 'e27217ff30b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_name', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('missing_required_columns_count', sa.Integer(), nullable=False),
    sa.Column('empty_blocking_values_count', sa.Integer(), nullable=False),
    sa.Column('invalid_type_values_count', sa.Integer(), nullable=False),
    sa.Column('invalid_datetime_values_count', sa.Integer(), nullable=False),
    sa.Column('invalid_reference_values_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validation_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_issues')
    op.drop_table('validation_runs')
    # ### end Alembic commands ###
