"""create salary features table

Revision ID: 55c0b3b1f058
Revises: 648628f9cbe5
Create Date: 2026-05-04 20:08:58.587056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c0b3b1f058'
down_revision: Union[str, Sequence[str], None] = '648628f9cbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.DateTime(), nullable=False),
    sa.Column('salary_mid', sa.Float(), nullable=False),
    sa.Column('salary_is_specified', sa.Boolean(), nullable=False),
    sa.Column('company_salary_median_by_city', sa.Float(), nullable=False),
    sa.Column('market_salary_median_excl_company_by_city', sa.Float(), nullable=False),
    sa.Column('salary_ratio_to_market_by_city', sa.Float(), nullable=False),
    sa.Column('company_salary_median_by_profile', sa.Float(), nullable=False),
    sa.Column('market_salary_median_excl_company_by_profile', sa.Float(), nullable=False),
    sa.Column('salary_ratio_to_market_by_profile', sa.Float(), nullable=False),
    sa.Column('company_salary_median_by_city_profile', sa.Float(), nullable=False),
    sa.Column('market_salary_median_excl_company_by_city_profile', sa.Float(), nullable=False),
    sa.Column('salary_ratio_to_market_by_city_profile', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_run_id', 'client_id', 'company_id', 'vacancy_id', 'date_day', name='uq_salary_features_feature_run_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_features')
    # ### end Alembic commands ###
