"""create categorical features table

Revision ID: 6e86abc8cd7e
Revises: bd72bfa9f95c
Create Date: 2026-05-06 18:00:35.996335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e86abc8cd7e'
down_revision: Union[str, Sequence[str], None] = 'bd72bfa9f95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorical_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=255), nullable=False),
    sa.Column('work_experience', sa.String(length=255), nullable=False),
    sa.Column('work_schedule', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_run_id', 'client_id', 'company_id', 'vacancy_id', 'date_day', name='uq_categorical_features_feature_run_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorical_features')
    # ### end Alembic commands ###
