"""create client summaries table

Revision ID: 776649bb9c85
Revises: 8301b3a74088
Create Date: 2026-05-03 22:27:00.697975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776649bb9c85'
down_revision: Union[str, Sequence[str], None] = '8301b3a74088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_company_name', sa.String(length=255), nullable=False),
    sa.Column('client_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('client_vacancy_count', sa.Integer(), nullable=False),
    sa.Column('client_total_callbacks', sa.Integer(), nullable=False),
    sa.Column('client_avg_callbacks', sa.Float(), nullable=False),
    sa.Column('client_median_callbacks', sa.Float(), nullable=False),
    sa.Column('client_mode_city', sa.String(length=255), nullable=True),
    sa.Column('client_mode_region', sa.String(length=255), nullable=True),
    sa.Column('client_mode_profile', sa.String(length=255), nullable=True),
    sa.Column('client_mode_tariff', sa.String(length=255), nullable=True),
    sa.Column('client_mode_work_schedule', sa.String(length=255), nullable=True),
    sa.Column('client_mode_work_experience', sa.String(length=255), nullable=True),
    sa.Column('client_mode_employment_type', sa.String(length=255), nullable=True),
    sa.Column('client_median_salary_from', sa.Float(), nullable=True),
    sa.Column('client_median_salary_to', sa.Float(), nullable=True),
    sa.Column('client_salary_specified_share', sa.Float(), nullable=False),
    sa.Column('client_salary_missing_share', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analytics_run_id', name='uq_client_summaries_analytics_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_summaries')
    # ### end Alembic commands ###
