"""create market summaries table

Revision ID: 8301b3a74088
Revises: 3fee09f2292a
Create Date: 2026-05-03 00:17:51.034942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8301b3a74088'
down_revision: Union[str, Sequence[str], None] = '3fee09f2292a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('total_company_count', sa.Integer(), nullable=False),
    sa.Column('total_vacancy_count', sa.Integer(), nullable=False),
    sa.Column('total_callbacks', sa.Integer(), nullable=False),
    sa.Column('avg_callbacks', sa.Float(), nullable=False),
    sa.Column('median_callbacks', sa.Float(), nullable=False),
    sa.Column('mode_city', sa.String(length=255), nullable=True),
    sa.Column('mode_region', sa.String(length=255), nullable=True),
    sa.Column('mode_profile', sa.String(length=255), nullable=True),
    sa.Column('mode_tariff', sa.String(length=255), nullable=True),
    sa.Column('mode_work_schedule', sa.String(length=255), nullable=True),
    sa.Column('mode_work_experience', sa.String(length=255), nullable=True),
    sa.Column('mode_employment_type', sa.String(length=255), nullable=True),
    sa.Column('median_salary_from', sa.Float(), nullable=True),
    sa.Column('median_salary_to', sa.Float(), nullable=True),
    sa.Column('salary_specified_share', sa.Float(), nullable=False),
    sa.Column('salary_missing_share', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analytics_run_id', name='uq_market_summaries_analytics_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_summaries')
    # ### end Alembic commands ###
