"""create vacancy snapshots table

Revision ID: b1164fc9acb6
Revises: 9de11c13e241
Create Date: 2026-04-27 13:25:36.348524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1164fc9acb6'
down_revision: Union[str, Sequence[str], None] = '9de11c13e241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vacancy_title', sa.String(length=255), nullable=False),
    sa.Column('vacancy_description', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('tariff', sa.String(length=255), nullable=True),
    sa.Column('work_experience', sa.String(length=255), nullable=True),
    sa.Column('work_schedule', sa.String(length=255), nullable=True),
    sa.Column('standard', sa.Integer(), nullable=False),
    sa.Column('standard_plus', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Integer(), nullable=False),
    sa.Column('callbacks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'company_id', 'vacancy_id', 'date_day', name='uq_vacancy_snapshots_client_company_vacancy_date_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_snapshots')
    # ### end Alembic commands ###
