"""create competitor summaries table

Revision ID: b12cf01c5609
Revises: 776649bb9c85
Create Date: 2026-05-03 22:36:20.047708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12cf01c5609'
down_revision: Union[str, Sequence[str], None] = '776649bb9c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analytics_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('competitor_company_count', sa.Integer(), nullable=False),
    sa.Column('competitor_snapshot_count', sa.Integer(), nullable=False),
    sa.Column('competitor_vacancy_count', sa.Integer(), nullable=False),
    sa.Column('competitor_total_callbacks', sa.Integer(), nullable=False),
    sa.Column('competitor_avg_callbacks', sa.Float(), nullable=False),
    sa.Column('competitor_median_callbacks', sa.Float(), nullable=False),
    sa.Column('competitor_mode_city', sa.String(length=255), nullable=True),
    sa.Column('competitor_mode_region', sa.String(length=255), nullable=True),
    sa.Column('competitor_mode_profile', sa.String(length=255), nullable=True),
    sa.Column('competitor_mode_tariff', sa.String(length=255), nullable=True),
    sa.Column('competitor_mode_work_schedule', sa.String(length=255), nullable=True),
    sa.Column('competitor_mode_work_experience', sa.String(length=255), nullable=True),
    sa.Column('competitor_mode_employment_type', sa.String(length=255), nullable=True),
    sa.Column('competitor_median_salary_from', sa.Float(), nullable=True),
    sa.Column('competitor_median_salary_to', sa.Float(), nullable=True),
    sa.Column('competitor_salary_specified_share', sa.Float(), nullable=False),
    sa.Column('competitor_salary_missing_share', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analytics_run_id'], ['analytics_runs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analytics_run_id', name='uq_competitor_summaries_analytics_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitor_summaries')
    # ### end Alembic commands ###
