"""create time features table

Revision ID: bd72bfa9f95c
Revises: 2e3d4fd10f05
Create Date: 2026-05-05 23:42:37.991385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd72bfa9f95c'
down_revision: Union[str, Sequence[str], None] = '2e3d4fd10f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.DateTime(), nullable=False),
    sa.Column('publication_hour', sa.Integer(), nullable=False),
    sa.Column('publication_day_of_week', sa.Integer(), nullable=False),
    sa.Column('publication_month', sa.Integer(), nullable=False),
    sa.Column('publication_week', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('vacancy_age_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_run_id', 'client_id', 'company_id', 'vacancy_id', 'date_day', name='uq_time_features_feature_run_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_features')
    # ### end Alembic commands ###
