"""create publication activity features table

Revision ID: c18fb53b8693
Revises: 55c0b3b1f058
Create Date: 2026-05-04 21:47:14.109573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18fb53b8693'
down_revision: Union[str, Sequence[str], None] = '55c0b3b1f058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_activity_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.DateTime(), nullable=False),
    sa.Column('publication_activity_level', sa.Integer(), nullable=False),
    sa.Column('days_since_last_publication_activity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_run_id', 'client_id', 'company_id', 'vacancy_id', 'date_day', name='uq_publication_activity_features_feature_run_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_activity_features')
    # ### end Alembic commands ###
