ML_TRAINING_STATUS_SUCCESS = 'success'
ML_TRAINING_STATUS_FAILED = 'failed'
ML_TRAINING_STATUS_NO_DATA = 'no_data'

ML_MODEL_TYPE_CATBOOST_REGRESSOR = 'catboost_regressor'
ML_TARGET_CALLBACKS = 'callbacks'

MIN_TRAINING_ROW_COUNT = 10
RANDOM_SEED = 42
TEST_SIZE = 0.2
